// Pin content for the tools_launch_2026 Pinterest batch.
// Every headline/fact below is taken verbatim (or lightly reworded, never renumbered)
// from src/content/tools.ts — the same copy already published and reviewed on the
// live calculator pages. No numbers here were invented for this campaign.

const BASE = "https://www.powermatchlab.com";
const CAMPAIGN = "tools_launch_2026";

function utm(path, content) {
  return `${BASE}${path}?utm_source=pinterest&utm_medium=social&utm_campaign=${CAMPAIGN}&utm_content=${content}`;
}

const REFRIGERATOR_PATH = "/tools/refrigerator-runtime-calculator";
const CPAP_PATH = "/tools/cpap-battery-calculator";
const STARLINK_PATH = "/tools/starlink-runtime-calculator";

export const PINS = [
  // ---------- Refrigerator (10) ----------
  {
    id: "fridge-01-formula",
    topic: "refrigerator",
    eyebrow: "FREE CALCULATOR",
    headline: "The Real Formula Behind Fridge Backup Power Sizing",
    subhead: "(daily energy × days of outage) ÷ usable efficiency × (1 + reserve) — enter your own numbers",
    title: "The Real Formula for Sizing Backup Power for a Refrigerator",
    description:
      "Recommended minimum capacity = (daily energy in Wh × days of outage) ÷ usable efficiency × (1 + reserve). Enter your fridge's own running watts and hours, and the free calculator shows which power stations actually meet it.",
    board: "Power Outage Prep",
    alt: "Formula diagram for calculating how much power station capacity a refrigerator needs during an outage",
    url: utm(REFRIGERATOR_PATH, "pin_fridge_01"),
    disclosure: true,
  },
  {
    id: "fridge-02-duty-cycle",
    topic: "refrigerator",
    eyebrow: "COMMON MISTAKE",
    headline: "Your Fridge Doesn't Run 24 Hours a Day — Your Math Shouldn't Either",
    subhead: "Compressors cycle on and off; using 24h/day overstates daily energy by 2-3×",
    title: "Why Refrigerator Power Calculations Should Use \"Equivalent Hours,\" Not 24",
    description:
      "A refrigerator's compressor cycles on and off — using 24 hours/day in your math overstates daily energy by 2-3×. The free calculator uses equivalent running hours instead, and lets you enter your own metered figure if you have one.",
    board: "Power Outage Prep",
    alt: "Explanation graphic showing why refrigerator compressors cycle instead of running continuously for 24 hours",
    url: utm(REFRIGERATOR_PATH, "pin_fridge_02"),
    disclosure: true,
  },
  {
    id: "fridge-03-surge",
    topic: "refrigerator",
    eyebrow: "OFTEN OVERLOOKED",
    headline: "Enough Continuous Watts Doesn't Mean the Station Can Start Your Fridge",
    subhead: "Compressor startup can briefly draw 2-3× the running watts",
    title: "Why Surge Rating Matters More Than Continuous Output for a Refrigerator",
    description:
      "A power station with plenty of continuous output but a low surge rating can still fail to start a refrigerator's compressor. Enter your unit's real surge figure (from the nameplate) into the free calculator for an accurate check.",
    board: "Power Outage Prep",
    alt: "Diagram showing refrigerator compressor startup surge versus continuous running watts",
    url: utm(REFRIGERATOR_PATH, "pin_fridge_03"),
    disclosure: true,
  },
  {
    id: "fridge-04-two-units",
    topic: "refrigerator",
    eyebrow: "FREE CALCULATOR",
    headline: "Running a Fridge AND a Freezer on One Power Station?",
    subhead: "Add both as separate rows — it sums continuous demand and takes the largest single surge",
    title: "Can One Power Station Run Both a Refrigerator and a Freezer?",
    description:
      "It depends on combined continuous output and worst-case surge. Add both units as separate rows in the free calculator so it sums continuous demand and takes the largest single startup surge on top.",
    board: "Power Outage Prep",
    alt: "Illustration of a refrigerator and a freezer both connected to one portable power station",
    url: utm(REFRIGERATOR_PATH, "pin_fridge_04"),
    disclosure: true,
  },
  {
    id: "fridge-05-solar",
    topic: "refrigerator",
    eyebrow: "SOLAR + OUTAGE",
    headline: "Solar Panels During an Outage: What They Actually Change",
    subhead: "Solar reduces the daily energy your battery must supply — not the instant power it must deliver",
    title: "How Solar Recharge Changes Refrigerator Power Station Sizing",
    description:
      "Enter a realistic daily Wh solar estimate and the free calculator treats it as reducing the energy your battery must supply each day — not the instantaneous power it has to deliver on demand.",
    board: "Solar + Off-Grid Power",
    alt: "Diagram of solar panels recharging a power station that is running a refrigerator during a power outage",
    url: utm(REFRIGERATOR_PATH, "pin_fridge_05"),
    disclosure: true,
  },
  {
    id: "fridge-06-nameplate",
    topic: "refrigerator",
    eyebrow: "COMMON MISTAKE",
    headline: "That Wattage Sticker on Your Fridge Is a Legal Maximum, Not Its Real Draw",
    subhead: "Nameplate wattage overstates average running draw — use a metered figure if you can",
    title: "Nameplate Wattage vs. Real Running Watts on a Refrigerator",
    description:
      "A manufacturer's nameplate wattage is a legal maximum, usually higher than the real average running draw. The free calculator lets you enter a metered or EnergyGuide figure instead of guessing from the sticker.",
    board: "Power Outage Prep",
    alt: "Close-up of a refrigerator nameplate wattage label next to a plug-in energy meter",
    url: utm(REFRIGERATOR_PATH, "pin_fridge_06"),
    disclosure: true,
  },
  {
    id: "fridge-07-faq-watts",
    topic: "refrigerator",
    eyebrow: "HOW MANY WATTS?",
    headline: "How Many Watts Does a Refrigerator Actually Use?",
    subhead: "Commonly 100-200W running, full-size unit — with 2-3× startup surge",
    title: "How Many Watts Does a Full-Size Refrigerator Use?",
    description:
      "It varies by size, age and efficiency — commonly 100-200W running for a full-size unit, with startup surge 2-3× higher. Check your own rating label or EnergyGuide sticker, then size backup power with the free calculator.",
    board: "Power Outage Prep",
    alt: "Infographic showing typical refrigerator running watts and startup surge range",
    url: utm(REFRIGERATOR_PATH, "pin_fridge_07"),
    disclosure: true,
  },
  {
    id: "fridge-08-door-closed",
    topic: "refrigerator",
    eyebrow: "DID YOU KNOW",
    headline: "Keeping the Door Closed Changes Your Power Math",
    subhead: "Fewer door openings = fewer compressor cycles = lower “equivalent hours/day”",
    title: "Does Keeping the Refrigerator Door Closed Change Power Station Sizing?",
    description:
      "Keeping doors closed reduces how often the compressor runs to hold temperature — exactly what “equivalent hours per day” estimates. The free calculator lets that field reflect your own usage pattern.",
    board: "Power Outage Prep",
    alt: "Illustration of a closed refrigerator door with a compressor cycle indicator",
    url: utm(REFRIGERATOR_PATH, "pin_fridge_08"),
    disclosure: true,
  },
  {
    id: "fridge-09-for-whom",
    topic: "refrigerator",
    eyebrow: "PLANNING AHEAD",
    headline: "From a Few Hours of Grocery Protection to a Multi-Day Outage",
    subhead: "Size backup power for exactly the scenario you're planning for",
    title: "Backup Power Planning for a Refrigerator or Freezer, Any Outage Length",
    description:
      "Whether you're protecting groceries for a few hours or planning for a multi-day outage with partial solar recharge, the free refrigerator runtime calculator scales to your real scenario — not a generic default.",
    board: "Power Outage Prep",
    alt: "Illustration of a refrigerator and freezer with a timeline showing outage duration options",
    url: utm(REFRIGERATOR_PATH, "pin_fridge_09"),
    disclosure: true,
  },
  {
    id: "fridge-10-cta",
    topic: "refrigerator",
    eyebrow: "NO SIGNUP",
    headline: "Free Refrigerator Runtime Calculator — Your Numbers, Not Guesses",
    subhead: "Enter watts, hours and outage days — see which power stations actually meet it",
    title: "Free Refrigerator & Freezer Runtime Calculator",
    description:
      "Enter your refrigerator's running watts, hours per day, and outage length — the free calculator shows the capacity and output you need, and which catalog power stations actually meet it. No signup, no invented prices.",
    board: "Power Outage Prep",
    alt: "Screenshot-style graphic of the free refrigerator and freezer power station runtime calculator",
    url: utm(REFRIGERATOR_PATH, "pin_fridge_10"),
    disclosure: true,
  },

  // ---------- CPAP (10) ----------
  {
    id: "cpap-01-formula",
    topic: "cpap",
    eyebrow: "FREE CALCULATOR",
    headline: "How Many Nights Will a Power Station Really Run Your CPAP?",
    subhead: "nights ≈ (station capacity × usable efficiency) ÷ (CPAP watts × hours/night)",
    title: "How Many Nights Can a Power Station Run a CPAP Machine?",
    description:
      "Estimated nights = (station capacity × usable efficiency) ÷ (CPAP watts × hours per night). Enter your machine's own consumption and the free calculator shows nights per product — not a generic guess.",
    board: "CPAP Travel & Backup Power",
    alt: "Formula diagram for calculating how many nights a power station can run a CPAP machine",
    url: utm(CPAP_PATH, "pin_cpap_01"),
    disclosure: true,
  },
  {
    id: "cpap-02-no-universal",
    topic: "cpap",
    eyebrow: "GOOD TO KNOW",
    headline: "There's No Single “CPAP Wattage” — Here's Why",
    subhead: "Base machines commonly range roughly 15-60W before humidifier or tubing draw",
    title: "Why There's No Universal CPAP Power Draw Number",
    description:
      "CPAP power draw depends on brand, model, pressure setting, and altitude compensation — published base-machine figures commonly range from roughly 15 to 60W. Check your own rating label, then use the free calculator.",
    board: "CPAP Travel & Backup Power",
    alt: "Graphic showing the range of CPAP machine power draw depending on brand and settings",
    url: utm(CPAP_PATH, "pin_cpap_02"),
    disclosure: true,
  },
  {
    id: "cpap-03-humidifier",
    topic: "cpap",
    eyebrow: "OFTEN MISSED",
    headline: "Your Heated Humidifier Adds More Power Than You'd Think",
    subhead: "A heated humidifier can add roughly 20-60W on top of the base CPAP machine",
    title: "How Much Power Does a CPAP Heated Humidifier Add?",
    description:
      "A heated humidifier can add roughly 20-60W depending on heat setting, and a heated tube adds further draw on top. The free calculator has separate toggles for both instead of one guessed combined number.",
    board: "CPAP Travel & Backup Power",
    alt: "Illustration of a CPAP machine with heated humidifier and heated tube power draw callouts",
    url: utm(CPAP_PATH, "pin_cpap_03"),
    disclosure: true,
  },
  {
    id: "cpap-04-ac-vs-dc",
    topic: "cpap",
    eyebrow: "AC VS DC",
    headline: "Running Your CPAP on DC Power Can Skip a Conversion Loss",
    subhead: "Direct 12V/24V DC is typically more efficient than AC inverter power — check compatibility first",
    title: "CPAP on AC Inverter Power vs. Direct DC — What Changes",
    description:
      "Running a CPAP through an AC inverter loses some energy to conversion. Many machines also accept a direct 12V/24V DC cable, which skips that step — check your machine's compatibility, then compare in the free calculator.",
    board: "CPAP Travel & Backup Power",
    alt: "Diagram comparing CPAP machine running on AC inverter power versus direct DC power",
    url: utm(CPAP_PATH, "pin_cpap_04"),
    disclosure: true,
  },
  {
    id: "cpap-05-not-medical-advice",
    topic: "cpap",
    eyebrow: "IMPORTANT",
    headline: "This Tool Calculates Runtime — It's Not Medical Advice",
    subhead: "Talk to your equipment provider or physician about backup power for your specific therapy needs",
    title: "Is a CPAP Battery Runtime Calculator Medical Advice? (No.)",
    description:
      "This free tool calculates estimated battery runtime from the numbers you enter — it does not assess therapy adequacy or medical suitability. Talk to your equipment provider or physician about backup power planning.",
    board: "CPAP Travel & Backup Power",
    alt: "Disclosure graphic clarifying that a CPAP power calculator is not medical advice",
    url: utm(CPAP_PATH, "pin_cpap_05"),
    disclosure: true,
  },
  {
    id: "cpap-06-generic-40w",
    topic: "cpap",
    eyebrow: "COMMON MISTAKE",
    headline: "Stop Using “40 Watts” for Every CPAP Model",
    subhead: "Use your own machine's rating label instead of a generic figure",
    title: "Why a Generic 40W CPAP Figure Is Usually Wrong",
    description:
      "Using a generic “40W” figure for every CPAP model instead of your actual machine's rating label is one of the most common sizing mistakes. Find your real number, then run it through the free calculator.",
    board: "CPAP Travel & Backup Power",
    alt: "Graphic warning against using a generic 40 watt figure for all CPAP machines",
    url: utm(CPAP_PATH, "pin_cpap_06"),
    disclosure: true,
  },
  {
    id: "cpap-07-humidifier-mistake",
    topic: "cpap",
    eyebrow: "COMMON MISTAKE",
    headline: "Forgetting Humidifier Draw Can Understate Power Needs by 50%+",
    subhead: "Add humidifier and heated-tube watts on top of the base machine, not instead of it",
    title: "How Much Does Skipping Humidifier Draw Understate CPAP Power Needs?",
    description:
      "Forgetting humidifier or heated-tube draw can understate real CPAP power consumption by 50% or more. The free calculator adds both on top of your base machine wattage automatically.",
    board: "CPAP Travel & Backup Power",
    alt: "Graphic showing how forgetting CPAP humidifier power draw understates total energy needs",
    url: utm(CPAP_PATH, "pin_cpap_07"),
    disclosure: true,
  },
  {
    id: "cpap-08-find-draw",
    topic: "cpap",
    eyebrow: "WHERE TO LOOK",
    headline: "Where to Find Your CPAP's Actual Power Draw",
    subhead: "Check the rating label, power brick, or manufacturer spec sheet — or use a plug-in meter",
    title: "Where to Find Your CPAP Machine's Real Power Consumption",
    description:
      "Check the rating label on the machine or its power supply/brick, or the manufacturer's published spec sheet. A plug-in energy meter gives the most accurate real-world average for the free calculator.",
    board: "CPAP Travel & Backup Power",
    alt: "Illustration pointing to a CPAP power supply label as the source of real wattage",
    url: utm(CPAP_PATH, "pin_cpap_08"),
    disclosure: true,
  },
  {
    id: "cpap-09-altitude",
    topic: "cpap",
    eyebrow: "GOOD TO KNOW",
    headline: "Altitude and Pressure Settings Can Change CPAP Power Draw",
    subhead: "Higher prescribed pressure or altitude compensation makes the motor work harder",
    title: "Does Altitude Affect CPAP Machine Power Consumption?",
    description:
      "A higher prescribed pressure or active altitude compensation makes the CPAP motor work harder. If your documentation gives a range, use the higher end in the free calculator for a more conservative estimate.",
    board: "CPAP Travel & Backup Power",
    alt: "Graphic showing altitude and pressure setting effects on CPAP machine power draw",
    url: utm(CPAP_PATH, "pin_cpap_09"),
    disclosure: true,
  },
  {
    id: "cpap-10-cta",
    topic: "cpap",
    eyebrow: "NO SIGNUP",
    headline: "Free CPAP Battery Runtime Calculator — Camping, Travel, Outages",
    subhead: "Enter your machine's real numbers, see nights per power station",
    title: "Free CPAP Battery Runtime Calculator",
    description:
      "Enter your CPAP's own wattage, humidifier and tube settings, and hours per night — the free calculator shows Wh needed and how many nights each catalog power station could realistically cover.",
    board: "CPAP Travel & Backup Power",
    alt: "Screenshot-style graphic of the free CPAP battery runtime calculator tool",
    url: utm(CPAP_PATH, "pin_cpap_10"),
    disclosure: true,
  },

  // ---------- Starlink (10) ----------
  {
    id: "starlink-01-formula",
    topic: "starlink",
    eyebrow: "FREE CALCULATOR",
    headline: "How Many Watt-Hours Does Starlink Really Use Off-Grid?",
    subhead: "daily energy ≈ average watts × hours of use per day — enter your own measured number",
    title: "How Many Watt-Hours Does Starlink Use Per Day?",
    description:
      "Daily energy (Wh) = average watts × hours of use per day. Enter your own measured Starlink consumption or a labeled example profile, and the free calculator shows the battery capacity you actually need.",
    board: "Starlink & Off-Grid Connectivity",
    alt: "Formula diagram for calculating daily Starlink energy consumption off-grid",
    url: utm(STARLINK_PATH, "pin_starlink_01"),
    disclosure: true,
  },
  {
    id: "starlink-02-cold-weather",
    topic: "starlink",
    eyebrow: "WINTER WARNING",
    headline: "Cold Weather Can Roughly Double Starlink's Power Draw",
    subhead: "Active snow-melt heating substantially increases average consumption",
    title: "Does Cold Weather Double Starlink's Power Consumption?",
    description:
      "Active snow-melt heating draws substantially more power than normal operation — commonly cited as roughly double the typical average. Use the heating-active profile in the free calculator for winter planning.",
    board: "Starlink & Off-Grid Connectivity",
    alt: "Graphic showing Starlink dish snow-melt heating increasing power consumption in winter",
    url: utm(STARLINK_PATH, "pin_starlink_02"),
    disclosure: true,
  },
  {
    id: "starlink-03-continuous-vs-scheduled",
    topic: "starlink",
    eyebrow: "BIG DIFFERENCE",
    headline: "Continuous vs. Scheduled Starlink Use Changes Your Power Math a Lot",
    subhead: "Powering on only for work hours can substantially reduce the capacity you need",
    title: "Starlink Continuous Operation vs. Scheduled Use: Power Impact",
    description:
      "Running Starlink 24 hours/day uses far more daily energy than scheduled use. If your setup allows powering on only when needed, entering realistic hours/day in the free calculator can substantially cut required capacity.",
    board: "Starlink & Off-Grid Connectivity",
    alt: "Comparison graphic of Starlink continuous operation versus scheduled hours of use",
    url: utm(STARLINK_PATH, "pin_starlink_03"),
    disclosure: true,
  },
  {
    id: "starlink-04-router",
    topic: "starlink",
    eyebrow: "OFTEN MISSED",
    headline: "Don't Forget the Router When Sizing Starlink Power",
    subhead: "A router can add a few watts to 15-20W or more on top of the dish",
    title: "How Much Power Does a Router Add on Top of Starlink?",
    description:
      "It depends on the router — anywhere from a few watts for a low-power travel router to 15-20W or more for a full-featured unit. Enter your router's own rating in the free calculator rather than assuming it's already included.",
    board: "Starlink & Off-Grid Connectivity",
    alt: "Illustration of a Starlink dish and router with separate power draw callouts",
    url: utm(STARLINK_PATH, "pin_starlink_04"),
    disclosure: true,
  },
  {
    id: "starlink-05-dc-bypass",
    topic: "starlink",
    eyebrow: "AC VS DC",
    headline: "A DC-to-DC Adapter Can Skip Inverter Losses for Starlink",
    subhead: "Bypassing the AC inverter avoids conversion loss — check hardware compatibility first",
    title: "Can You Run Starlink Directly on DC Power?",
    description:
      "Some setups use a DC-to-DC adapter to bypass a power station's AC inverter, avoiding conversion losses. Check compatibility with your Starlink hardware, then use the AC/DC toggle in the free calculator as a starting point.",
    board: "Starlink & Off-Grid Connectivity",
    alt: "Diagram comparing Starlink running on AC inverter power versus a DC-to-DC bypass adapter",
    url: utm(STARLINK_PATH, "pin_starlink_05"),
    disclosure: true,
  },
  {
    id: "starlink-06-not-one-number",
    topic: "starlink",
    eyebrow: "GOOD TO KNOW",
    headline: "Starlink Power Draw Isn't One Number — Here's What Changes It",
    subhead: "Hardware generation, dish size, ambient temperature and duty cycle all matter",
    title: "Why Starlink Power Consumption Isn't a Single Fixed Number",
    description:
      "Average consumption differs by hardware generation and dish size, and rises substantially during active heating. Enter your own measured average from a plug-in energy meter into the free calculator for the most reliable number.",
    board: "Starlink & Off-Grid Connectivity",
    alt: "Graphic explaining the factors that change Starlink power consumption",
    url: utm(STARLINK_PATH, "pin_starlink_06"),
    disclosure: true,
  },
  {
    id: "starlink-07-solar-deficit",
    topic: "starlink",
    eyebrow: "SOLAR + STARLINK",
    headline: "How Solar Changes the Battery Capacity Starlink Off-Grid Needs",
    subhead: "Daily deficit after solar = max(0, daily energy − daily solar Wh)",
    title: "Sizing Battery Capacity for Starlink Off-Grid With Solar",
    description:
      "The free calculator nets your daily solar contribution against Starlink's daily energy need, then sizes capacity for the remaining deficit across your planned days off-grid — not a blended guess.",
    board: "Starlink & Off-Grid Connectivity",
    alt: "Diagram showing solar panels offsetting Starlink's daily energy needs off-grid",
    url: utm(STARLINK_PATH, "pin_starlink_07"),
    disclosure: true,
  },
  {
    id: "starlink-08-for-whom",
    topic: "starlink",
    eyebrow: "WHO THIS IS FOR",
    headline: "Sizing Battery Power for Starlink: Remote Work, Travel, Preparedness",
    subhead: "Off-grid travelers, remote workers, and emergency-preparedness planners",
    title: "Who Needs a Starlink Battery Runtime Calculator?",
    description:
      "Off-grid travelers, remote workers, and emergency-preparedness planners all need to size battery capacity differently for a Starlink kit. The free calculator adapts to your own days-off-grid and solar input.",
    board: "Starlink & Off-Grid Connectivity",
    alt: "Illustration of Starlink used for remote work, travel, and emergency preparedness",
    url: utm(STARLINK_PATH, "pin_starlink_08"),
    disclosure: true,
  },
  {
    id: "starlink-09-measured-vs-example",
    topic: "starlink",
    eyebrow: "MORE ACCURATE",
    headline: "Measured Starlink Consumption Beats Any Example Profile",
    subhead: "Example profiles are clearly labeled starting points — not a spec for your exact hardware",
    title: "Should You Use Your Own Measured Starlink Power Draw?",
    description:
      "The example profiles in the free calculator are clearly labeled starting points, not a specification for any particular Starlink hardware revision. Your own plug-in-meter measurement gives the most reliable number.",
    board: "Starlink & Off-Grid Connectivity",
    alt: "Graphic comparing a measured Starlink power reading to a generic example profile",
    url: utm(STARLINK_PATH, "pin_starlink_09"),
    disclosure: true,
  },
  {
    id: "starlink-10-cta",
    topic: "starlink",
    eyebrow: "NO SIGNUP",
    headline: "Free Starlink Runtime Calculator for Off-Grid Setups",
    subhead: "Your own numbers or a labeled example — see the capacity you actually need",
    title: "Free Starlink Runtime Calculator",
    description:
      "Enter your own measured Starlink consumption (or a clearly labeled example profile), set days off-grid and any solar input — the free calculator shows capacity needed and which catalog products can deliver it.",
    board: "Starlink & Off-Grid Connectivity",
    alt: "Screenshot-style graphic of the free Starlink runtime calculator tool",
    url: utm(STARLINK_PATH, "pin_starlink_10"),
    disclosure: true,
  },
];
